name       : clutter
version    : 1.26.0
release    : 16
source     :
    - http://ftp.gnome.org/pub/gnome/sources/clutter/1.26/clutter-1.26.0.tar.xz : 67514e7824b3feb4723164084b36d6ce1ae41cb3a9897e9f1a56c8334993ce06
license    :
    - LGPL-2.1
summary    : OpenGL UI toolkit
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(cogl-1.0)
    - pkgconfig(cairo-gobject)
    - pkgconfig(atk)
    - pkgconfig(pangocairo)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libinput)
description: |
    Clutter is an open source (LGPL 2.1) software library for creating fast, compelling, portable, and dynamic graphical user interfaces. It is a core part of Gnome3, it is used by the GnomeShell, and is supported by the open source community.
setup      : |
    %configure --disable-static \
               --enable-x11-backend \
               --enable-gdk-backend \
               --enable-wayland-backend \
               --enable-egl-backend \
               --enable-wayland-compositor \
               --enable-xinput \
               --enable-gdk-pixbuf \
               --enable-evdev-input \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
