name       : clutter
version    : 1.26.4
release    : 26
source     :
    - https://download.gnome.org/sources/clutter/1.26/clutter-1.26.4.tar.xz : 8b48fac159843f556d0a6be3dbfc6b083fc6d9c58a20a49a6b4919ab4263c4e6
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : OpenGL UI toolkit
description: |
    Clutter is an open source (LGPL 2.1) software library for creating fast, compelling, portable, and dynamic graphical user interfaces. It is a core part of Gnome3, it is used by the GnomeShell, and is supported by the open source community.
builddeps  :
    - pkgconfig(cogl-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libinput)
setup      : |
    %configure --disable-static \
               --enable-egl-backend \
               --enable-evdev-input \
               --enable-gdk-backend \
               --enable-gdk-pixbuf \
               --enable-introspection \
               --enable-wayland-backend \
               --enable-wayland-compositor \
               --enable-x11-backend \
               --enable-xinput
build      : |
    %make
install    : |
    %make_install
