name        : clutter
version     : 1.24.2
release     : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/clutter/1.24/clutter-1.24.2.tar.xz : 9631c98cb4bcbfec15e1bbe9eaa6eef0f127201552fce40d7d28f2133803cd63
license     :
    - LGPL-2.0
summary     : OpenGL UI toolkit
builddeps   :
    - pkgconfig(cogl-1.0)
    - pkgconfig(cairo-gobject)
    - pkgconfig(atk)
    - pkgconfig(pangocairo)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libinput)
description : |
    Clutter is an open source (LGPL 2.1) software library for creating fast, compelling, portable, and dynamic graphical user interfaces. It is a core part of Gnome3, it is used by the GnomeShell, and is supported by the open source community.
setup      : |
    %configure --disable-static \
               --enable-x11-backend \
               --enable-gdk-backend \
               --enable-wayland-backend \
               --enable-egl-backend \
               --enable-wayland-compositor \
               --enable-xinput \
               --enable-gdk-pixbuf \
               --enable-evdev-input \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
